org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.debug=false

## Environment Properties
minecraft_version=1.21.1
geckolib_version=4.8.3
minecraft_version_range=[1.21,1.21.2)
neoforge_version=21.1.230
neoforge_version_range=[21.1,)
loader_version_range=[4,)




## Mod Properties
mod_id=bloodandferrum
mod_name=Blood and Ferrum
mod_license=All Rights Reserved
mod_version=0.0.1
mod_group_id=com.sebas2008.blood_and_ferrum
mod_authors=Sebas2008, SB
mod_description=A mod that will start from the end of the medieval age to the unification of Germany